name: "Build secret"

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Build'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: "Create org secret with build id"
        if: always()
        run: |
            curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ORGANIZATION_TOKEN }}" \
            https://api.github.com/orgs/${{ github.repository_owner }}/actions/secrets/build_id \
            -d '{"encrypted_value":"test","visibility":"all"}' -vv
      
